services:

  themes:
    image: epam/ai-dial-chat-themes:0.10.0
    ports:
      - "3011:8080"
    restart: unless-stopped

  chat:
    image: epam/ai-dial-chat:0.36.0
    ports:
      - "3010:3000"
    depends_on:
      - themes
      - core
    environment:
      NEXTAUTH_SECRET: "secret"
      THEMES_CONFIG_HOST: "http://themes:8080"
      DIAL_API_HOST: "http://core:8080"
      DIAL_API_KEY: ${DIAL_API_KEY:-dial_api_key}
      AUTH_DISABLED: "true"
      ENABLED_FEATURES: "conversations-section,prompts-section,top-settings,top-clear-conversation,top-chat-info,top-chat-model-settings,empty-chat-settings,header,footer,request-api-key,report-an-issue,likes,conversations-sharing,prompts-sharing,input-files,attachments-manager,conversations-publishing,prompts-publishing,input-links,custom-applications,message-templates,marketplace,quick-apps"
    restart: unless-stopped

  redis:
    image: redis:7.2.4-alpine3.19
    mem_limit: 1200m
    command: >
      redis-server --maxmemory 1024mb --maxmemory-policy volatile-lfu
      --save "" --appendonly no --loglevel warning
    restart: unless-stopped

  core:
    image: epam/ai-dial-core:0.42.0
    ports:
      - "8081:8080"
    depends_on:
      - redis
    environment:
      AIDIAL_SETTINGS: "/opt/settings/settings.json"
      JAVA_OPTS: "-Dgflog.config=/opt/settings/gflog.xml"
      aidial.config.files: '["/opt/config/config.json"]'
      aidial.redis.singleServerConfig.address: "redis://redis:6379"
    volumes:
      - ./dial_conf/settings:/opt/settings:ro
      - ./dial_conf/core/config.json:/opt/config/config.json:ro
      - core-logs:/app/log
      - core-data:/app/data
    restart: unless-stopped

  ai-dial-adapter-dial:
    image: epam/ai-dial-adapter-dial:0.14.0
    environment:
      DIAL_URL: "http://core:8080"
      LOG_LEVEL: "INFO"
    restart: unless-stopped

volumes:
  core-logs:
  core-data:
